[package]
name = "tap_graph"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "The Graph TAP receipt structs"

[dependencies]
alloy.workspace = true
serde.workspace = true
rand.workspace = true
thiserror.workspace = true
tap_eip712_message = { version = "0.1.0", path = "../tap_eip712_message" }
tap_receipt = { version = "0.1.0", path = "../tap_receipt" }


[dev-dependencies]
rstest.workspace = true


[features]
default = []
v2 = []
